<a href="https://colab.research.google.com/github/Samujjalborah/python-learning-journey/blob/main/Day6_NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 6 - NumPy Practice

## Objective

This notebook demonstrates the basic features of NumPy for numerical data analysis, including array creation, indexing, slicing, reshaping, mathematical operations, broadcasting, boolean masking, and aggregate functions.

**Developed by:** Samujjal Borah

## 1. Creating NumPy Arrays

In [12]:
import numpy as np
arr1 = np.array([10,20,30,40,50])

arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr1)
print(arr2)
print(arr3)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2. Dimensions and Data Types

In [13]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.dtype)
print(arr2.dtype)

1
2
3
int64
int64


## 3. Indexing and Slicing

In [14]:
print(arr1[2])

print(arr2[1,2])

print(arr1[1:4])

print(arr2[:,1])

30
6
[20 30 40]
[2 5]


## 4. Reshaping Arrays

In [15]:
arr = np.arange(12)

print(arr)

reshaped = arr.reshape(3,4)

print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 5. Creating Arrays using NumPy Functions

In [16]:
print(np.zeros((2,3)))

print(np.ones((3,2)))

print(np.arange(1,11))

print(np.linspace(0,1,5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


## 6. Mathematical Operations

In [17]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(a**2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


## 7. Vectorized Operations

In [18]:
arr = np.array([10,20,30])

print(arr+5)

print(arr*2)

print(np.sqrt(arr))

print(np.sin(arr))

[15 25 35]
[20 40 60]
[3.16227766 4.47213595 5.47722558]
[-0.54402111  0.91294525 -0.98803162]


## 8. Boolean Masking

In [19]:
arr = np.array([12,5,30,18,7,25])

mask = arr>15

print(mask)

print(arr[mask])

[False False  True  True False  True]
[30 18 25]


## 9. Broadcasting

In [20]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr+10)

[[11 12 13]
 [14 15 16]]


## 10. Aggregate Functions

In [21]:
arr = np.array([10,20,30,40,50])

print("Sum:",np.sum(arr))

print("Mean:",np.mean(arr))

print("Minimum:",np.min(arr))

print("Maximum:",np.max(arr))

print("Median:",np.median(arr))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


# Conclusion

This notebook demonstrates the fundamental operations of NumPy including array creation, indexing, slicing, reshaping, mathematical operations, broadcasting, boolean masking, and aggregate functions. These concepts form the foundation for scientific computing, data analysis, and machine learning in Python.